[package]
name = "oh-my-droid"
version = "0.5.1"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = "4.5.45"
dirs = "6.0.0"
owo-colors = "4.2.2"
serde = { version = "1.0.219", features = ["serde_derive", "derive"] }
serde_yml = "0.0.12"
toml = "0.9.5"
url = "2.5.6"
